#!/bin/sh
echo "executing pre-commit"
# count number of commits
current_version=$(sed -n '/version/ s/.*"[0-9]\+\.[0-9]\+\.\([0-9]\+\)".*/\1/p' pyproject.toml)
new_version=$((current_version + 1))
sed -i '/version/ s/\("[0-9]\+\.[0-9]\+\.\)[0-9]\+"/\1'"$new_version"'/g' pyproject.toml

git add 'pyproject.toml'