#!/bin/sh
echo "executing pre-commit"
# count number of commits
current_version=$(sed -n 's/\(version = "\([0-9]*\.[0-9]*\.\)\([0-9]*\)"/\3/p' pyproject.toml)
new_version=$((current_version + 1))

sed -i "s/\(version = \"\([0-9]*\.[0-9]*\.\)\)$current_version\"/\2$new_version\"/" pyproject.toml

git add 'pyproject.toml'