# Generated by Django 4.2.8 on 2024-01-24 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slurpit_netbox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slurpitimporteddevice',
            name='changeddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slurpitimporteddevice',
            name='slurpit_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='slurpitstageddevice',
            name='changeddate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slurpitstageddevice',
            name='slurpit_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
