# Generated by Django 4.2.7 on 2023-12-02 10:53

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0098_webhook_custom_field_data_webhook_tags'),
        ('slurpit_netbox', '0002_create_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('external_id', models.CharField(max_length=32)),
                ('name', models.CharField(editable=False, max_length=100, unique=True)),
                ('disabled', models.BooleanField(editable=False)),
                ('last_synced', models.DateTimeField(blank=True, editable=False, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slurpit_netbox.source')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
