# Generated by Django 4.2.8 on 2023-12-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slurpit_netbox', '0003_slurpitlog_tags_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='connection_status',
            field=models.CharField(default='', editable=False, max_length=50, null=True),
        ),
    ]
