# Generated by Django 4.2.8 on 2023-12-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slurpit_netbox', '0004_setting_connection_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slurpitlog',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='slurpitlog',
            name='created',
        ),
        migrations.RemoveField(
            model_name='slurpitlog',
            name='custom_field_data',
        ),
        migrations.RemoveField(
            model_name='slurpitlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='slurpitlog',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='slurpitlog',
            name='tags',
        ),
    ]
