# Generated by Django 4.2.8 on 2024-01-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slurpit_netbox', '0006_importeddevice_airflow_importeddevice_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='push_api_key',
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
    ]
