# Generated by Django 4.2.8 on 2024-01-09 08:42

from django.db import migrations, models
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0105_customfield_min_max_values'),
        ('slurpit_netbox', '0007_setting_push_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningDataTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('index', models.TextField(max_length=20, unique=True)),
                ('name', models.TextField(max_length=255, null=True)),
                ('flags', models.TextField(max_length=10, null=True)),
                ('type', models.TextField(max_length=50, null=True)),
                ('act_mtu', models.TextField(max_length=50, null=True)),
                ('l2_mtu', models.TextField(max_length=50, null=True)),
                ('max_mtu', models.TextField(max_length=50, null=True)),
                ('mac_addr', models.TextField(max_length=50, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
