# Generated by Django 4.2.8 on 2024-01-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slurpit_netbox', '0008_planningdatatab'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlurpitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255, null=True)),
                ('slurpit_plan_id', models.TextField(max_length=10, unique=True)),
            ],
        ),
    ]
