# Generated by Django 4.2.8 on 2024-01-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slurpit_netbox', '0009_slurpitplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slurpitplan',
            old_name='slurpit_plan_id',
            new_name='plan_id',
        ),
    ]
