# Generated by Django 4.2.8 on 2024-01-10 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slurpit_netbox', '0011_slurpitplan_comments_slurpitplan_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slurpitplan',
            name='display',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
