# Generated by Django 4.2.8 on 2024-01-15 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slurpit_netbox', '0012_slurpitplan_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='slurpitplan',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
