# Generated by Django 4.2.8 on 2024-01-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slurpit_netbox', '0013_slurpitplan_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slurpitplan',
            name='display',
        ),
    ]
