# Generated by Django 4.2.9 on 2024-01-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0105_customfield_min_max_values'),
        ('slurpit_netbox', '0015_slurpitdevice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlurpitDevice',
            new_name='Snapshot',
        ),
    ]
