# Generated by Django 5.0.6 on 2024-08-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slurpit_netbox", "0015_slurpitinterface_ignore_duplex_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="slurpitprefix",
            name="ignore_description",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="slurpitprefix",
            name="ignore_role",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="slurpitprefix",
            name="ignore_site",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="slurpitprefix",
            name="ignore_status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="slurpitprefix",
            name="ignore_tenant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="slurpitprefix",
            name="ignore_vlan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="slurpitprefix",
            name="ignore_vrf",
            field=models.BooleanField(default=False),
        ),
    ]
