# Generated by Django 4.2.8 on 2024-01-20 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slurpit_netbox', '0017_remove_importeddevice_airflow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='importeddevice',
            name='added',
        ),
        migrations.RemoveField(
            model_name='stageddevice',
            name='added',
        ),
    ]
