# Generated by Django 4.2.9 on 2024-01-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slurpit_netbox', '0018_remove_importeddevice_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='appliance_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
