# Generated by Django 4.2.8 on 2024-01-22 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0185_gfk_indexes'),
        ('slurpit_netbox', '0018_remove_importeddevice_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importeddevice',
            name='mapped_device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcim.device'),
        ),
    ]
