# Generated by Django 4.2.9 on 2024-01-23 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slurpit_netbox', '0019_setting_appliance_type'),
        ('slurpit_netbox', '0020_alter_importeddevice_mapped_device'),
    ]

    operations = [
    ]
